server:
    port: 8080
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    datasource:
        url: jdbc:postgresql://localhost:5432/lctesdb
        password: admin
        username: admin
        driverClassName: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate.jdbc.batch_size: 20
            hibernate.cache.use_query_cache: false
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_structured_entries: false
            hibernate.cache.use_minimal_puts: false
    security:
        user:
            name: admin
            password: admin
            roles: ADMIN, USER, MANAGER